### ISSUE TITLE
Compilation failed with pull request #4

### ISSUE THREAD

**Issue by robervalwalsh** [desy-cms/analysis#8]
@ShevchenkoRostyslav 
The compilation failed after merging pull [request #4](https://github.com/desy-cms/analysis/pull/4). 

```
Analysis/MssmHbb/bin/doubleBTagSelection.cc: In function 'int main(int, char**)':
Analysis/MssmHbb/bin/doubleBTagSelection.cc:143:24: error: 'class analysis::mssmhbb::MssmHbb' has no member named 'eventTree'
    fileName = analysis.eventTree()->GetFile()->GetName();
                        ^
gmake: *** [tmp/slc6_amd64_gcc491/src/Analysis/MssmHbb/bin/doubleBTagSelection/doubleBTagSelection.o] Error 1
```

**Temporary solution**
- [x] Commented out the lines compiling the macros in Analysis/MssmHbb/bin/BuildFile.xml
- [x] Committed to develop

**To do**
- [ ] Fix the macros, test them and make another pull request.

**Comment by ShevchenkoRostyslav** [comment]
Your temporary solution is enough for time binning. 
That was a part of the code from my own repo. Another pull request isn't needed

**Comment by robervalwalsh** [comment]
Ok.
